CREATE TABLE IF NOT EXISTS parcel (
    number BIGINT AUTO_INCREMENT PRIMARY KEY,
    client INT NOT NULL,
    status VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
